image: Ubuntu1804 # образдлясборки
stack: node 10 #окружение
cache: node_modules #кеширование
install:
 - npm install #командаустановкизависимостей
build: off
build_script:
-npm run build #командасборки
test_script:
- npm run lint && npm test #скрипттестирования
deploy_script: #скриптразвёртывания
- git config --global credential.helper store
- git config --global user.name AppVeyor
- git config --global user.emailci@appveyor.com
- echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
- npx push-dir --dir=dist --branch=gh-pages --force --verbose